spring:
  datasource:
    url: jdbc:mysql://localhost:3306/syspsi
    username: USERSYSPSIAPP
    password: zM1vxBTcDcBgmE576nl8beZFlAZeaQJn
    
backup:
  salvarEm: C:\Users\marcelo.lima\Desktop\backup
  mysql:
    path: C:\Program Files\MySQL\MySQL Server 5.7\bin