USE `syspsi`;
CREATE TABLE IF NOT EXISTS `syspsi`.`backup` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fim` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;